### ISSUE TITLE
Demos on website don't work on new Nexus 7

### ISSUE THREAD

**Issue by theirf** [furf/jquery-ui-touch-punch#112] opened 2013-08-02 20:58 UTC
The draggable demos on the website do not work on the new nexus 7 running chrome as the browser.

Here is the URL I am visiting and I am trying to drag the square, but I can't: http://touchpunch.furf.com/

**Comment by theirf** [comment] 2013-08-02 20:58
It works on iPad Mini, but not new Nexus 7

**Comment by GabiAxel** [comment] 2013-08-09 22:09
Same here. It does work with Firefox and Opera on Nexus 7, just not Chrome.

**Comment by mikesir87** [comment] 2013-08-14 03:06
I imagine that this is a duplicate of Issue #99 - have you tried running these from some other site?  When opening the site in Chrome and connecting to the remote debugger using ADB, I get the following console error:

Refused to execute script from 'https://raw.github.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 

So, looks like the punch js library isn't even loaded on Chrome in Android.  Should work on your own site just fine.

**Comment by Molkobain** [comment] 2013-11-13 10:14
Yes, like said on another issue, you have to host the js file properly and not include it from github.

**Comment by ghost** [comment] 2013-11-13 17:29
@theirf do you have a working example with ios7?

**Comment by theirf** [comment] 2013-11-13 18:18
@shigella Yes. I have it working on Nexus 7 and iOS7 now.

I can't show my example as it is a private, unreleased site, but this should help:

This is the copy of touchPunch that I am using: https://gist.github.com/theirf/c9bcf146713e69a0f578

Here is what one of my instances of draggable looks like:

```
var originalTopValue = null;
        $('.settings').draggable({
            axis: 'y',
            start: function(event, ui){
                originalTopValue = ui.position.top;
            },
            drag: function(event, ui){
                if(originalTopValue > ui.position.top){
                    return false;
                }
            }
        });
```

On all the draggable elements, I also have this style, which helps:

```
-ms-touch-action: none;
```

Hope this helps!

**Comment by ghost** [comment] 2013-11-13 18:46
hey thanks i will look at it tommorow!..Does this also work for autocomplete?

**Comment by theirf** [comment] 2013-11-13 19:15
Haven't tested autocomplete yet.

But let me know if it does!

**Comment by sebastianzillessen** [comment] 2013-11-25 08:36
Same For me, did not work on Android 4.4, Nexus 4 or 10. 

The issue was the import from raw.github!

**NEVER USER https://raw.github.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js ON YOUR SIDE!!!**

**Closed as completed** 2014-02-05 18:07 UTC
