### ISSUE TITLE
Not working on Samsung Galaxy Note 2 with Chrome

### ISSUE THREAD

**Issue by brunocramos** [furf/jquery-ui-touch-punch#108] opened 2013-07-24 10:30 UTC
I've tried your examples on my Samsung Galaxy Note 2 with Chrome but all the drag and drop and resize examples don't work on my smartphone. I even tested on your own site with your examples. It simply does nothing.
Any clue about it?

**Comment by mikesir87** [comment] 2013-08-14 03:07
Duplicate of Issue #99 - Chrome doesn't load the resource based on its MIME type sent from the GitHub server

**Closed as completed** 2014-02-05 18:05 UTC
