### ISSUE TITLE
NO EVENT WORKS with new version of chrome for android (before this it was OK!)

### ISSUE THREAD

**Issue by elvisbegovic** [furf/jquery-ui-touch-punch#105] opened 2013-07-16 11:13 UTC
Before it worked fine but now nothing works & that with all android devices... I tried it directly on plugin's website: http://touchpunch.furf.com/ and FAIL !!!

(it's OK with iphone & firefox :| )

My config:
Last OS version on Nexus7' or Galaxy S4
Last chrome version
Last jquery plugin
Last jqueryui plugin

**Comment by mikesir87** [comment] 2013-08-14 03:08
Duplicate of Issue #99 - Chrome for Android does not execute the punch js file due to the MIME type sent from the GitHub server.

**Closed as completed** 2014-02-05 18:05 UTC
