### ISSUE TITLE
Doesn't work on Chrome (Desktop)

### ISSUE THREAD

**Issue by derek1906** [furf/jquery-ui-touch-punch#132] opened 2013-12-29 23:59 UTC
It seems like that the hack doesn't apply if the client is on a desktop/laptop. All demos don't work on my machine (Chrome 32, Windows 8). They work if I use the mouse but don't work when I use the touchscreen as the input.

There's also an error

```
Refused to execute script from 'https://raw.github.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 
```

However it doesn't seem to be the problem because it works on Chrome for iOS/Android.

**Comment by togakangaroo** [comment] 2014-01-02 21:26
I have the same issue. Got my big new touchscreen monitor and touchpunch doesn't work in chrome.

As for the script error, that is what happens when you try to use github as a cdn.

**Comment by furf** [comment] 2014-02-05 16:05
I believe this is a duplicate of #139.

**Closed as completed by furf** 2014-02-05 16:05 UTC
